export default [
  {
    id: 1,
    postedOn: "2024-02-04",
    title: "Frontend Developer",
    company: "Atlassian",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["Javascript", "ReactJS", "Taiwind CSS", "GraphQL"],
    job_link: "https://www.atlassian.com/company/careers",
  },
  {
    id: 2,
    postedOn: "2024-02-08",
    title: "Full-Stack Developer",
    company: "Tower Research",
    type: "Full Time",
    experience: "Entry Level",
    location: "In-Office",
    skills: [
      "Javascript",
      "ReactJS",
      "NodeJs",
      "GraphQL",
      "ExpressJS",
      "MongoDB",
    ],
    job_link: "https://www.atlassian.com/company/careers",
  },
  {
    id: 3,
    postedOn: "2024-02-10",
    title: "iOS Developer",
    company: "Apple",
    type: "Full Time",
    experience: "Senior Level",
    location: "Remote",
    skills: ["Swift", "UIKit", "UiData", "Kotlin"],
    job_link: "https://www.atlassian.com/company/careers",
  },
  {
    id: 4,
    postedOn: "2024-02-04",
    title: "DevOps Developer",
    company: "Deel.com",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["Javascript", "ReactJS", "NodeJs", "GraphQL", "ExpressJS"],
    job_link: "https://www.atlassian.com/company/careers",
  },
];
